# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Generation

on:
  pull_request:
    types: [closed]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Update NuGet package
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/ashiryn/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build
      run: |
        cd Logging
        dotnet pack -c Release -o out
        
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./Logging/out/*.nupkg -k ${NUGET_AUTH_TOKEN} -s https://nuget.pkg.github.com/ashiryn --skip-duplicate --no-symbols true
